### ISSUE TITLE
Can I 

### ISSUE THREAD

**Issue by jspille** [jkanev/treetime#2]
You wrote: "Linked trees are a natural and powerful way to structure data." - Can I change and add Trees?

**Comment by jkanev** [comment]
Sorry jspille, seen your question only now.

You have a forest (multiple trees), sharing nodes. From the GUI, you can add and change and remove branches and nodes in a tree, assign them to any other tree you like, change a node's contents, etc.

If you want to add an entire tree to the forest, or remove it, or re-define the fields that are calculated from the data, you have to edit your data file. This is possible with a standard text editor, and it's what I do, but it's not really user friendly. I didn't get round to write a GUI for this yet.

However, syntax is not that hard. If you look at the simple-task-list.trt file I think you can guess most of the stuff. I'll write a syntax description within the next days, and of course a GUI for this is planned too.

Hope that helps?
All the best, Jacob.

**Comment by jkanev** [comment]
Dear jspille --

with the last release the picture has changed a bit. We now have an editor that lets you add and remove trees, define the tree fields and choose calculations, and add and remove data fields. Here's a description how this works: https://treetime-data-manager.readthedocs.io/en/latest/meta-structure.html.

The project is moving to codeberg.org, away from github, and you can find the last release here: https://codeberg.org/jkanev/treetime/releases, or on PyPi by doing "pip install TreeTime" on the command line (if you want to use Python).

Hope that helps, Jacob.
