### ISSUE TITLE
running TreeTime for the first time

### ISSUE THREAD

**Issue by rhaynes74** [jkanev/treetime#3]
Hi, looks like a nice tool. I installed treetime and can run the executable, but then it pops up a dialog asking me for a directory or a file?    I tried providing a directory but no dice.  How do I proceed?

**Comment by jkanev** [comment]
Hi rhaynes74,

it asks you for a file to load. The file defines the number of trees, the fields in the data items, and the calculated fields. 
The data is stored in *.trt files (basically text files). Even when creating something new you start with an empty file. There are three example files provided in the data directory. You can also make your own, or I can send some more examples if you like.

Unfortunately there isn't a lot of documentation on the syntax yet, sorry about that...

All the best, Jacob.

   ______________________________________
   Jacob Kanev
   Sweetmorn, 26th of Chaos, 3188

**Comment by rhaynes74** [comment]
Thanks. - I will check it out!

Sincerely,

Dr. Ronald D. Haynes
Professor, Department of Mathematics and Statistics
Chair, MSc and Phd Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by jkanev** [comment]
Dear Ronald Haynes,
just curious whether this has worked for you, and/or whether there's anything else I can do for you.

All the best, Jacob.

   ______________________________________
   Jacob Kanev
      email: ***@***.***  |  threema: MXET6S4P
      instagram: j_kanev | twitter: @j_kanev  | jabber: ***@***.***
      web: http://jkanev.info  |  blog: http://jacobkanev.wordpress.com

**Comment by rhaynes74** [comment]
Hi Jacob - thanks for the message.   I haven’t had a chance to try this yet.  Would it be possible to provide a default setup with the installation?

Sincerely,

Dr. Ronald D. Haynes
Professor, Department of Mathematics and Statistics
Chair, MSc and Phd Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by jkanev** [comment]
Dear Ronald Haynes,

yes, of course, the package was meant to be complete. I must have missed this when testing. :)

I'll double check to make sure this is part of all the packages. Did you use one of the zip files, or did you install via pip?

All the best, Jacob.

   ______________________________________
   Jacob Kanev
      email: ***@***.***  |  threema: MXET6S4P
      instagram: j_kanev | twitter: @j_kanev  | jabber: ***@***.***
      web: http://jkanev.info  |  blog: http://jacobkanev.wordpress.com

**Comment by rhaynes74** [comment]
Hi - thanks for the reply.  I tried the .zip file if I recall, but either is fine.

Sincerely,

Dr. Ronald D. Haynes
Professor, Department of Mathematics and Statistics
Chair, MSc and Phd Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by jkanev** [comment]
Brilliant, thanks for the quick reply. I'll notify you as soon as I have something new.

All the best, Jacob.

   ______________________________________
   Jacob Kanev
      email: ***@***.***  |  threema: MXET6S4P
      instagram: j_kanev | twitter: @j_kanev  | jabber: ***@***.***
      web: http://jkanev.info  |  blog: http://jacobkanev.wordpress.com

**Comment by jkanev** [comment]
Dear Ronald Haynes,

Sorry for not notifying your earlier.
I double checked the data directory in the Windows zip file and it was indeed empty. This is now fixed in today's release, https://github.com/jkanev/treetime/releases/tag/2023.1 . Also, since the previous release (2022.1), when starting the software for the first time, a dialog comes up that explaines to load a file first.
I also started to flesh out the documentation a bit (https://treetime-data-manager.readthedocs.io/en/latest/data-format.html) so you can start creating new (or adapting existing) trt files.
Hope this helps?

All the best, Jacob
