### ISSUE TITLE
windows download

### ISSUE THREAD

**Issue by NiloofarVaghefi** [jkanev/treetime#4]
Hi there
I have downloaded the windows version and unzip it bur the data folder seems to be empty?
Thanks
Niloofar

**Comment by jkanev** [comment]
Oh, that's bad. Thanks for telling me. I'll re-do the installer within the next days and notify you.
In the mean time you can also grab some data (.trt) files directly from github: https://github.com/jkanev/treetime/tree/master/data 

All the best, Jacob.

**Comment by jkanev** [comment]
Dear Niloofar,
in the latest windows installer (https://github.com/jkanev/treetime/releases/tag/2023.1) the data directory is non-empty. Please have a look.

All the best, Jacob.
